### ISSUE TITLE
Upload v0.2.0 documentation to Pursuit

### ISSUE THREAD

**Issue by kl0tl** [coot/purescript-argonaut-aeson-generic#9]
The latest version of this library isn’t available on Pursuit yet, is there any improvement being worked on or is that an oversight?

According to https://pursuit.purescript.org/help/authors I should be able to upload the documentation myself but I wanted to ask first out of courtesy.

**Comment by StephenWakely** [comment]
It is an oversight. If you can upload it that would be very much appreciated!

**Comment by StephenWakely** [comment]
@kl0tl Sorry about the delay. I have merged the pr, and tagged the latest as v0.3.0 so hopefully it should work now..

**Comment by kl0tl** [comment]
I just published the v0.3.0 on Pursuit: https://pursuit.purescript.org/packages/purescript-argonaut-aeson-generic/0.3.0 🎉
